package com.kbers.alert;

/**
 * <a href="mailto:joyriver7@gmail.com">Jinxi Hong</a> 2017/4/22 18:29
 */
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import com.amzass.database.DBManager;
import com.amzass.service.common.ApplicationContext;
import com.google.inject.Inject;
import com.kbers.alert.AllAccountLists.allCountList;
import com.kbers.alert.Indicators.InfringementRecord;
import org.nutz.dao.Cnd;
import org.nutz.dao.Condition;

import java.util.List;

/**
 *
 * @author ACC18-8
 */
public class AutoEmailOld extends javax.swing.JFrame {

    @Inject
    DBManager dbManager;

    /**
     * Creates new form NewJFrame
     */
    public AutoEmailOld() {
        initComponents();

//        InfringementCaseRecordDownloading Infringement = ApplicationContext.getBean(InfringementCaseRecordDownloading.class);
//        Infringement.clearInfringement();
//        Infringement.loadInfringement();
//
//        AllAccountListDownloading InfringementX = ApplicationContext.getBean(AllAccountListDownloading.class);
//        InfringementX.clearAllAccountList();
//        InfringementX.loadAllCountList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(240, 240, 140));

        jLabel3.setText("keyword:");
        jLabel3.setToolTipText("");
        jLabel3.setRequestFocusEnabled(false);

        jLabel5.setText("infrigement No.");
        jLabel5.setToolTipText("");

        setTitle("自动邮件模板Tool");

        jButton1.setText("生成模板");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel15.setText("AmazonEmail:");
        jLabel15.setToolTipText("");

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(137, 137, 137)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel5)
                                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(64, 64, 64)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addGap(213, 213, 213)
                                .addComponent(jButton1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel15))
                                .addGap(42, 42, 42)
                                .addComponent(jButton1)
                                .addGap(39, 39, 39)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.getAccessibleContext().setAccessibleName("keyword:");

        pack();
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        System.out.println("This is the first one! ");
        System.out.println("This is the first one! ");
//        jTextField1.setText("Jinxi Hong");
        String IDI =   jTextField5.getText().trim();
        System.out.println("IDI:"+IDI);
        int idi = Integer.valueOf(IDI);



//        Connection connection = null;
//        try {
//            connection = DriverManager.getConnection("jdbc:sqlite:db/orderman.db");
//            Statement statement = connection.createStatement();
//            statement.setQueryTimeout(30);
//           String [] s = new String [100];
////            java.sql.Array sd
//       ResultSet ss= statement.executeQuery("SELECT * FROM Infringement  WHERE IDI='" + idi+"'").getArray(0).getResultSet();
//           System.out.println(ss);
//            System.out.println("IDI"+ IDI +"," +" successful!");
//        } catch (SQLException e) {
//            e.printStackTrace();
//        }
//        Condition cndInfringement = Cnd.where("IDI", "like", 12);
//        List<InfringementRecord> InfringementRecordList = dbManager.query(InfringementRecord.class, cndInfringement);
//        Condition cndInfringement = Cnd.where("ACC", "like", IDI);
//        List<InfringementRecord> InfringementRecordList = dbManager.query(InfringementRecord.class, cndInfringement);

        String keyword2 = jTextField3.getText();
        List<InfringementRecord> InfringementRecordList = de(idi);

//        try {
//            Thread.sleep(10000);
//        } catch (InterruptedException e) {
//            e.printStackTrace();
//        }

        String accountName = InfringementRecordList.get(0).ACC;
        String ReceivedDate = InfringementRecordList.get(0).ReceiveDate;
        String ROEmail = InfringementRecordList.get(0).OwnerEmail;
        String ROName = InfringementRecordList.get(0).OwnerName;
        String ASIN = InfringementRecordList.get(0).ASIN;
        String Type = InfringementRecordList.get(0).Type;
        String BrandName = InfringementRecordList.get(0).BrandName;
        String theFristEmail = InfringementRecordList.get(0).FirstEmail;
        String Backup = InfringementRecordList.get(0).Backup;
        String WorkerName = InfringementRecordList.get(0).WorkerName;
        String ComplaintWithdrawn = InfringementRecordList.get(0).ComplaintWithdrawn;
        String WithdrawingDate = InfringementRecordList.get(0).WithdrawingDate;
        String WithdrawnBy = InfringementRecordList.get(0).WithdrawnBy;
        String Space = "  ";
        String keyword1 = BrandName;

        String infrigement =  IDI+Space+accountName+Space+ReceivedDate+Space+ROEmail+Space;
        String  mark = theFristEmail;

        if(theFristEmail.matches(Constants.TINTEGER_REGX)) {
            String accountNameEU;
            if(accountName.contains("UK"))
                accountNameEU = accountName.replace("UK","EU");
            else if(accountName.contains("FR"))
                accountNameEU = accountName.replace("FR","EU");
            else if(accountName.contains("DE"))
                accountNameEU = accountName.replace("DE","EU");
            else if(accountName.contains("IT"))
                accountNameEU = accountName.replace("IT","EU");
            else if(accountName.contains("ES"))
                accountNameEU = accountName.replace("ES","EU");
            else
                accountNameEU = accountName;

            List<allCountList> AllAccountList = fr(accountNameEU);

            if (AllAccountList.size() != 0) {
                String StoreManagerName = AllAccountList.get(0).ManagerName;  //jTextField6.getText();
                String StoreName = AllAccountList.get(0).StoreName;   //jTextField8.getText();

                String title = BrandName;  //jTextField7.getText();
                String AmazonEmail = jTextField12.getText();
                String SellerEmail = AllAccountList.get(0).SellerGmail;         //jTextField10.getText();

                Template tplate = new Template();

                System.out.println("mark: " + mark);
                if (mark.contentEquals("T0"))
                    jTextArea1.setText(tplate.Template0(keyword1, keyword2, infrigement, ROName,
                            ROEmail, StoreManagerName, StoreName, ASIN,
                            title, AmazonEmail, SellerEmail, accountName));
                else if (mark.contentEquals("T1"))
                    jTextArea1.setText(tplate.Template1(keyword1, keyword2, infrigement, ROName,
                            ROEmail, StoreManagerName, StoreName, ASIN,
                            title, AmazonEmail, SellerEmail, accountName));
                else if (mark.contentEquals("T2"))
                    jTextArea1.setText(tplate.Template2(keyword1, keyword2, infrigement, ROName,
                            ROEmail, StoreManagerName, StoreName, ASIN,
                            title, AmazonEmail, SellerEmail, accountName));
                else if (mark.contentEquals("T3"))
                    jTextArea1.setText(tplate.Template3(keyword1, keyword2, infrigement, ROName,
                            ROEmail, StoreManagerName, StoreName, ASIN,
                            title, AmazonEmail, SellerEmail, accountName));
                else if (mark.contentEquals("T4"))
                    jTextArea1.setText(tplate.Template4(keyword1, keyword2, infrigement, ROName,
                            ROEmail, StoreManagerName, StoreName, ASIN,
                            title, AmazonEmail, SellerEmail, accountName));
                else if (mark.contentEquals("T5"))
                    jTextArea1.setText(tplate.Template5(keyword1, keyword2, infrigement, ROName,
                            ROEmail, StoreManagerName, StoreName, ASIN,
                            title, AmazonEmail, SellerEmail, accountName));
                else if (mark.contentEquals("T6"))
                    jTextArea1.setText(tplate.Template6(keyword1, keyword2, infrigement, ROName,
                            ROEmail, StoreManagerName, StoreName, ASIN,
                            title, AmazonEmail, SellerEmail, accountName));
                else if (mark.contentEquals("T7"))
                    jTextArea1.setText(tplate.Template7(keyword1, keyword2, infrigement, ROName,
                            ROEmail, StoreManagerName, StoreName, ASIN,
                            title, AmazonEmail, SellerEmail, accountName));
                else if (mark.contentEquals("T8"))
                    jTextArea1.setText(tplate.Template8(keyword1, keyword2, infrigement, ROName,
                            ROEmail, StoreManagerName, StoreName, ASIN,
                            title, AmazonEmail, SellerEmail, accountName));
                else if (mark.contentEquals("T9"))
                    jTextArea1.setText(tplate.Template9(keyword1, keyword2, infrigement, ROName,
                            ROEmail, StoreManagerName, StoreName, ASIN,
                            title, AmazonEmail, SellerEmail, accountName));
                else if (mark.contentEquals("T10"))
                    jTextArea1.setText(tplate.Template10(keyword1, keyword2, infrigement, ROName,
                            ROEmail, StoreManagerName, StoreName, ASIN,
                            title, AmazonEmail, SellerEmail, accountName));
                else if (mark.contentEquals("T11"))
                    jTextArea1.setText(tplate.Template11(keyword1, keyword2, infrigement, ROName,
                            ROEmail, StoreManagerName, StoreName, ASIN,
                            title, AmazonEmail, SellerEmail, accountName));
                else if (mark.contentEquals("T12"))
                    jTextArea1.setText(tplate.Template12(keyword1, keyword2, infrigement, ROName,
                            ROEmail, StoreManagerName, StoreName, ASIN,
                            title, AmazonEmail, SellerEmail, accountName));
                else if (mark.contentEquals("T13"))
                    jTextArea1.setText(tplate.Template13(keyword1, keyword2, infrigement, ROName,
                            ROEmail, StoreManagerName, StoreName, ASIN,
                            title, AmazonEmail, SellerEmail, accountName));
                else if (mark.contentEquals("T14"))
                    jTextArea1.setText(tplate.Template14(keyword1, keyword2, infrigement, ROName,
                            ROEmail, StoreManagerName, StoreName, ASIN,
                            title, AmazonEmail, SellerEmail, accountName));
                else if (mark.contentEquals("T15"))
                    jTextArea1.setText(tplate.Template15(keyword1, keyword2, infrigement, ROName,
                            ROEmail, StoreManagerName, StoreName, ASIN,
                            title, AmazonEmail, SellerEmail, accountName));
                else if (mark.contentEquals("T16"))
                    jTextArea1.setText(tplate.Template16(keyword1, keyword2, infrigement, ROName,
                            ROEmail, StoreManagerName, StoreName, ASIN,
                            title, AmazonEmail, SellerEmail, accountName));
                else if (mark.contentEquals("T100"))
                    jTextArea1.setText(tplate.Template100(keyword1, keyword2, infrigement, ROName,
                            ROEmail, StoreManagerName, StoreName, ASIN,
                            title, AmazonEmail, SellerEmail, accountName));
                else if (mark.contentEquals("T101"))
                    jTextArea1.setText(tplate.Template101(keyword1, keyword2, infrigement, ROName,
                            ROEmail, StoreManagerName, StoreName, ASIN,
                            title, AmazonEmail, SellerEmail, accountName));
                else if (mark.contentEquals("T102"))
                    jTextArea1.setText(tplate.Template102(keyword1, keyword2, infrigement, ROName,
                            ROEmail, StoreManagerName, StoreName, ASIN,
                            title, AmazonEmail, SellerEmail, accountName));
                else if (mark.contentEquals("T103"))
                    jTextArea1.setText(tplate.Template103(keyword1, keyword2, infrigement, ROName,
                            ROEmail, StoreManagerName, StoreName, ASIN,
                            title, AmazonEmail, SellerEmail, accountName));
            } else {
                jTextArea1.setText("No seller info!");
            }
        } else {
            jTextArea1.setText("Not need template request!");
        }

    }

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AutoEmailOld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AutoEmailOld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AutoEmailOld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutoEmailOld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ApplicationContext.getBean(AutoEmailOld.class).setVisible(true);
                System.out.println("This is the only one! ");
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration

    public List<InfringementRecord> de(int idi){
        Condition cndInfringement = Cnd.where("IDI", "like", idi);

//        try {
//            Thread.sleep(10000);
//        } catch (InterruptedException e) {
//            e.printStackTrace();
//        }
        List<InfringementRecord> InfringementRecordList = dbManager.query(InfringementRecord.class, cndInfringement);

        System.out.println(InfringementRecordList);

        return InfringementRecordList;
    }

    public List<allCountList> fr(String acc){
//        acc = "26UK";
        Condition cndInfringement = Cnd.where("ACC", "like", acc);
        List<allCountList> InfringementRecordList = dbManager.query(allCountList.class, cndInfringement);
        System.out.println(InfringementRecordList);
        return InfringementRecordList;
    }
}

