/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kbers.alert;

import com.amzass.database.DBManager;
import com.amzass.service.common.ApplicationContext;
import com.google.inject.Inject;
import com.kbers.alert.AllAccountLists.allCountList;
import com.kbers.alert.Indicators.InfringementRecord;
import org.nutz.dao.Cnd;
import org.nutz.dao.Condition;
import org.nutz.dao.util.cri.SqlExpressionGroup;


import java.sql.*;
import java.util.List;

/**
 *
 * @author ACC18-8
 */
public class JavaSwing extends javax.swing.JFrame {

    @Inject
    DBManager dbManager;

    /**
     * Creates new form JavaSwing
     */
    public JavaSwing() {
        initComponents();

        InfringementCaseRecordDownloading Infringement = ApplicationContext.getBean(InfringementCaseRecordDownloading.class);
        Infringement.clearInfringement();
        Infringement.loadInfringement();

        AllAccountListDownloading InfringementX = ApplicationContext.getBean(AllAccountListDownloading.class);
//        InfringementX.clearAllAccountList();
        InfringementX.loadAllCountList();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(240, 240, 140));

        jLabel1.setText("keyword1:");

        jLabel3.setText("keyword2:");
        jLabel3.setToolTipText("");

        jLabel5.setText("infrigement No.");
        jLabel5.setToolTipText("");

        jLabel6.setText("StoreManagerName:");
        jLabel6.setToolTipText("");

        jButton1.setText("生成模板");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }

        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"T 1", "T 2", "T 3", "T 4","T 5", "T 6", "T 7", "T 8",
                "T 9", "T 10", "T 11", "T 12","T 13", "T 14", "T 15", "T 16","T 100", "T 101", "T 102", "T 103"
        }));

        jLabel7.setText("Blank1:");
        jLabel7.setToolTipText("");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel9.setText("title:");
        jLabel9.setToolTipText("");

        jLabel11.setText("StoreName:");
        jLabel11.setToolTipText("");

        jLabel15.setText("AmazonEmail:");
        jLabel15.setToolTipText("");

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });

        jLabel16.setText("SellerEmail:");
        jLabel16.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel1)
                                                                .addGap(25, 25, 25)
                                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(13, 13, 13)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                                .addGap(65, 65, 65)
                                                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel3)
                                                                .addGap(25, 25, 25)
                                                                .addComponent(jTextField3)))
                                                .addGap(107, 107, 107)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel6)
                                                                        .addComponent(jLabel15))
                                                                .addGap(31, 31, 31)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(jTextField12)
                                                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel5)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(104, 104, 104)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel11)
                                                                        .addComponent(jLabel16))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(jTextField8)
                                                                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jTextField7)))))
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(359, 359, 359))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(134, 134, 134)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel7)
                                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel11)
                                                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(137, 137, 137)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel16)
                                                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel5)
                                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(66, 66, 66)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel6)
                                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel9)
                                                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(48, 48, 48)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel15))))
                                .addGap(63, 63, 63)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        System.out.println("This is the first one! ");
//        jTextField1.setText("Jinxi Hong");
        String IDI =   jTextField5.getText().trim();
        System.out.println("IDI:"+IDI);
        int idi = Integer.valueOf(IDI);

//        Connection connection = null;
//        try {
//            connection = DriverManager.getConnection("jdbc:sqlite:db/orderman.db");
//            Statement statement = connection.createStatement();
//            statement.setQueryTimeout(30);
//           String [] s = new String [100];
////            java.sql.Array sd
//       ResultSet ss= statement.executeQuery("SELECT * FROM Infringement  WHERE IDI='" + idi+"'").getArray(0).getResultSet();
//           System.out.println(ss);
//            System.out.println("IDI"+ IDI +"," +" successful!");
//        } catch (SQLException e) {
//            e.printStackTrace();
//        }
//        Condition cndInfringement = Cnd.where("IDI", "like", 12);
//        List<InfringementRecord> InfringementRecordList = dbManager.query(InfringementRecord.class, cndInfringement);
//        Condition cndInfringement = Cnd.where("ACC", "like", IDI);
//        List<InfringementRecord> InfringementRecordList = dbManager.query(InfringementRecord.class, cndInfringement);
        String keyword1 = jTextField1.getText();
        String keyword2 = jTextField3.getText();
        List<InfringementRecord> InfringementRecordList = de(idi);
//        try {
//            Thread.sleep(10000);
//        } catch (InterruptedException e) {
//            e.printStackTrace();
//        }

        String accountName = InfringementRecordList.get(0).ACC;
        String ReceivedDate = InfringementRecordList.get(0).ReceiveDate;
        String ROEmail = InfringementRecordList.get(0).OwnerEmail;
        String ROName = InfringementRecordList.get(0).OwnerName;
        String ASIN = InfringementRecordList.get(0).ASIN;
        String Type = InfringementRecordList.get(0).Type;
        String BrandName = InfringementRecordList.get(0).BrandName;
        String theFristEmail = InfringementRecordList.get(0).FirstEmail;
        String Backup = InfringementRecordList.get(0).Backup;
        String WorkerName = InfringementRecordList.get(0).WorkerName;
        String ComplaintWithdrawn = InfringementRecordList.get(0).ComplaintWithdrawn;
        String WithdrawingDate = InfringementRecordList.get(0).WithdrawingDate;
        String WithdrawnBy = InfringementRecordList.get(0).WithdrawnBy;
        String Space = "  ";


        String infrigement =  IDI+Space+accountName+Space+ReceivedDate+Space+ROEmail+Space+ROName;

        List<allCountList> AllAccountList = fr(accountName);

        String StoreManagerName = AllAccountList.get(0).ManagerName;  //jTextField6.getText();
        String StoreName = AllAccountList.get(0).StoreName;   //jTextField8.getText();

        String title = "";  //jTextField7.getText();
        String AmazonEmail = jTextField12.getText();
        String SellerEmail = AllAccountList.get(0).SellerGmail;         //jTextField10.getText();

        Template tplate = new Template();
        int mark = jComboBox1.getSelectedIndex();
        System.out.println("mark: "+mark);
        if(mark == 0)
            jTextArea1.setText(tplate.Template0(keyword1,  keyword2, infrigement,  ROName,
                    ROEmail,  StoreManagerName,  StoreName, ASIN,
                    title,  AmazonEmail,  SellerEmail,accountName));
        else if(mark == 1)
            jTextArea1.setText(tplate.Template1(keyword1,  keyword2, infrigement,  ROName,
                    ROEmail,  StoreManagerName,  StoreName, ASIN,
                    title,  AmazonEmail,  SellerEmail,accountName));
        else if(mark == 2)
            jTextArea1.setText(tplate.Template2(keyword1,  keyword2, infrigement,  ROName,
                    ROEmail,  StoreManagerName,  StoreName, ASIN,
                    title,  AmazonEmail,  SellerEmail,accountName));
        else if(mark == 3)
            jTextArea1.setText(tplate.Template3(keyword1,  keyword2, infrigement,  ROName,
                    ROEmail,  StoreManagerName,  StoreName, ASIN,
                    title,  AmazonEmail,  SellerEmail,accountName));
        else if(mark == 4)
            jTextArea1.setText(tplate.Template4(keyword1,  keyword2, infrigement,  ROName,
                    ROEmail,  StoreManagerName,  StoreName, ASIN,
                    title,  AmazonEmail,  SellerEmail,accountName));
        else if(mark == 5)
            jTextArea1.setText(tplate.Template5(keyword1,  keyword2, infrigement,  ROName,
                    ROEmail,  StoreManagerName,  StoreName, ASIN,
                    title,  AmazonEmail,  SellerEmail,accountName));
        else if(mark == 6)
            jTextArea1.setText(tplate.Template6(keyword1,  keyword2, infrigement,  ROName,
                    ROEmail,  StoreManagerName,  StoreName, ASIN,
                    title,  AmazonEmail,  SellerEmail,accountName));
        else if(mark == 7)
            jTextArea1.setText(tplate.Template7(keyword1,  keyword2, infrigement,  ROName,
                    ROEmail,  StoreManagerName,  StoreName, ASIN,
                    title,  AmazonEmail,  SellerEmail,accountName));
        else if(mark == 8)
            jTextArea1.setText(tplate.Template8(keyword1,  keyword2, infrigement,  ROName,
                    ROEmail,  StoreManagerName,  StoreName, ASIN,
                    title,  AmazonEmail,  SellerEmail,accountName));
        else if(mark == 9)
            jTextArea1.setText(tplate.Template9(keyword1,  keyword2, infrigement,  ROName,
                    ROEmail,  StoreManagerName,  StoreName, ASIN,
                    title,  AmazonEmail,  SellerEmail,accountName));
        else if(mark == 10)
            jTextArea1.setText(tplate.Template10(keyword1,  keyword2, infrigement,  ROName,
                    ROEmail,  StoreManagerName,  StoreName, ASIN,
                    title,  AmazonEmail,  SellerEmail,accountName));
        else if(mark == 11)
            jTextArea1.setText(tplate.Template11(keyword1,  keyword2, infrigement,  ROName,
                    ROEmail,  StoreManagerName,  StoreName, ASIN,
                    title,  AmazonEmail,  SellerEmail,accountName));
        else if(mark == 12)
            jTextArea1.setText(tplate.Template12(keyword1,  keyword2, infrigement,  ROName,
                    ROEmail,  StoreManagerName,  StoreName, ASIN,
                    title,  AmazonEmail,  SellerEmail,accountName));
        else if(mark == 13)
            jTextArea1.setText(tplate.Template13(keyword1,  keyword2, infrigement,  ROName,
                    ROEmail,  StoreManagerName,  StoreName, ASIN,
                    title,  AmazonEmail,  SellerEmail,accountName));
        else if(mark == 14)
            jTextArea1.setText(tplate.Template14(keyword1,  keyword2, infrigement,  ROName,
                    ROEmail,  StoreManagerName,  StoreName, ASIN,
                    title,  AmazonEmail,  SellerEmail,accountName));
        else if(mark == 15)
            jTextArea1.setText(tplate.Template15(keyword1,  keyword2, infrigement,  ROName,
                    ROEmail,  StoreManagerName,  StoreName, ASIN,
                    title,  AmazonEmail,  SellerEmail,accountName));
        else if(mark == 16)
            jTextArea1.setText(tplate.Template16(keyword1,  keyword2, infrigement,  ROName,
                    ROEmail,  StoreManagerName,  StoreName, ASIN,
                    title,  AmazonEmail,  SellerEmail,accountName));
        else if(mark == 17)
            jTextArea1.setText(tplate.Template100(keyword1,  keyword2, infrigement,  ROName,
                    ROEmail,  StoreManagerName,  StoreName, ASIN,
                    title,  AmazonEmail,  SellerEmail,accountName));
        else if(mark == 18)
            jTextArea1.setText(tplate.Template101(keyword1,  keyword2, infrigement,  ROName,
                    ROEmail,  StoreManagerName,  StoreName, ASIN,
                    title,  AmazonEmail,  SellerEmail,accountName));
        else if(mark == 19)
            jTextArea1.setText(tplate.Template102(keyword1,  keyword2, infrigement,  ROName,
                    ROEmail,  StoreManagerName,  StoreName, ASIN,
                    title,  AmazonEmail,  SellerEmail,accountName));
        else if(mark == 20)
            jTextArea1.setText(tplate.Template103(keyword1,  keyword2, infrigement,  ROName,
                    ROEmail,  StoreManagerName,  StoreName, ASIN,
                    title,  AmazonEmail,  SellerEmail,accountName));
    }


    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ApplicationContext.getBean(JavaSwing.class).setVisible(true);
                System.out.println("This is the only one! ");
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration

    public List<InfringementRecord> de(int idi){
        Condition cndInfringement = Cnd.where("IDI", "like", idi);

//        try {
//            Thread.sleep(10000);
//        } catch (InterruptedException e) {
//            e.printStackTrace();
//        }
        List<InfringementRecord> InfringementRecordList = dbManager.query(InfringementRecord.class, cndInfringement);

        System.out.println(InfringementRecordList);

        return InfringementRecordList;
    }

    public List<allCountList> fr(String acc){
        Condition cndInfringement = Cnd.where("ACC", "like", acc);
        List<allCountList> InfringementRecordList = dbManager.query(allCountList.class, cndInfringement);
        System.out.println(InfringementRecordList);
        return InfringementRecordList;
    }


}
